<?php
/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SwaggerPetstoreLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ApiResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var integer|null $code public property
     */
    public $code;

    /**
     * @todo Write general description for this property
     * @var string|null $type public property
     */
    public $type;

    /**
     * @todo Write general description for this property
     * @var string|null $message public property
     */
    public $message;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $code    Initialization value for $this->code
     * @param string  $type    Initialization value for $this->type
     * @param string  $message Initialization value for $this->message
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->code    = func_get_arg(0);
            $this->type    = func_get_arg(1);
            $this->message = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['code']    = $this->code;
        $json['type']    = $this->type;
        $json['message'] = $this->message;

        return $json;
    }
}
