<?php
/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SwaggerPetstoreLib\Models;

/**
 * OAuth 2 scopes supported by the API
 */
class OAuthScopeEnum
{
    /**
     * read your pets
     */
    const READPETS = "read:pets";

    /**
     * modify pets in your account
     */
    const WRITEPETS = "write:pets";
}
