<?php
/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SwaggerPetstoreLib\Models;

use JsonSerializable;
use SwaggerPetstoreLib\Utils\DateTimeHelper;

/**
 * @todo Write general description for this model
 */
class Order implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var integer|null $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @var integer|null $petId public property
     */
    public $petId;

    /**
     * @todo Write general description for this property
     * @var integer|null $quantity public property
     */
    public $quantity;

    /**
     * @todo Write general description for this property
     * @factory \SwaggerPetstoreLib\Utils\DateTimeHelper::fromRfc3339DateTime
     * @var \DateTime|null $shipDate public property
     */
    public $shipDate;

    /**
     * Order Status
     * @var string|null $status public property
     */
    public $status;

    /**
     * @todo Write general description for this property
     * @var bool|null $complete public property
     */
    public $complete;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer   $id       Initialization value for $this->id
     * @param integer   $petId    Initialization value for $this->petId
     * @param integer   $quantity Initialization value for $this->quantity
     * @param \DateTime $shipDate Initialization value for $this->shipDate
     * @param string    $status   Initialization value for $this->status
     * @param bool      $complete Initialization value for $this->complete
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->id       = func_get_arg(0);
            $this->petId    = func_get_arg(1);
            $this->quantity = func_get_arg(2);
            $this->shipDate = func_get_arg(3);
            $this->status   = func_get_arg(4);
            $this->complete = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']       = $this->id;
        $json['petId']    = $this->petId;
        $json['quantity'] = $this->quantity;
        $json['shipDate'] = isset($this->shipDate) ?
            DateTimeHelper::toRfc3339DateTime($this->shipDate) : null;
        $json['status']   = $this->status;
        $json['complete'] = $this->complete;

        return $json;
    }
}
