<?php
/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SwaggerPetstoreLib\Models;

/**
 * @todo Write general description for this enumeration
 */
class Status2Enum
{
    /**
     * TODO: Write general description for this element
     */
    const AVAILABLE = "available";

    /**
     * TODO: Write general description for this element
     */
    const PENDING = "pending";

    /**
     * TODO: Write general description for this element
     */
    const SOLD = "sold";
}
