<?php
/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SwaggerPetstoreLib\Models;

/**
 * Order Status
 */
class Status1Enum
{
    /**
     * TODO: Write general description for this element
     */
    const PLACED = "placed";

    /**
     * TODO: Write general description for this element
     */
    const APPROVED = "approved";

    /**
     * TODO: Write general description for this element
     */
    const DELIVERED = "delivered";
}
