<?php
/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SwaggerPetstoreLib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class User implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var integer|null $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @var string|null $username public property
     */
    public $username;

    /**
     * @todo Write general description for this property
     * @var string|null $firstName public property
     */
    public $firstName;

    /**
     * @todo Write general description for this property
     * @var string|null $lastName public property
     */
    public $lastName;

    /**
     * @todo Write general description for this property
     * @var string|null $email public property
     */
    public $email;

    /**
     * @todo Write general description for this property
     * @var string|null $password public property
     */
    public $password;

    /**
     * @todo Write general description for this property
     * @var string|null $phone public property
     */
    public $phone;

    /**
     * User Status
     * @var integer|null $userStatus public property
     */
    public $userStatus;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id         Initialization value for $this->id
     * @param string  $username   Initialization value for $this->username
     * @param string  $firstName  Initialization value for $this->firstName
     * @param string  $lastName   Initialization value for $this->lastName
     * @param string  $email      Initialization value for $this->email
     * @param string  $password   Initialization value for $this->password
     * @param string  $phone      Initialization value for $this->phone
     * @param integer $userStatus Initialization value for $this->userStatus
     */
    public function __construct()
    {
        if (8 == func_num_args()) {
            $this->id         = func_get_arg(0);
            $this->username   = func_get_arg(1);
            $this->firstName  = func_get_arg(2);
            $this->lastName   = func_get_arg(3);
            $this->email      = func_get_arg(4);
            $this->password   = func_get_arg(5);
            $this->phone      = func_get_arg(6);
            $this->userStatus = func_get_arg(7);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']         = $this->id;
        $json['username']   = $this->username;
        $json['firstName']  = $this->firstName;
        $json['lastName']   = $this->lastName;
        $json['email']      = $this->email;
        $json['password']   = $this->password;
        $json['phone']      = $this->phone;
        $json['userStatus'] = $this->userStatus;

        return $json;
    }
}
