<?php
/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SwaggerPetstoreLib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The environment being used'
     * @var string
     */
    public static $environment = Environments::PRODUCTION;

    /**
     * OAuth 2 Client ID
     * @var string
     */
    public static $oAuthClientId = 'TODO: Replace';

    /**
     * OAuth 2 Redirection endpoint or Callback Uri
     * @var string
     */
    public static $oAuthRedirectUri = 'TODO: Replace';

    /**
     * Get the base uri for a given server in the current environment
     * @param  string $server Server name
     * @return string         Base URI
     */
    public static function getBaseUri($server = Servers::SERVER1)
    {
        return APIHelper::appendUrlWithTemplateParameters(
            static::$environmentsMap[static::$environment][$server],
            array(
            )
        );
    }

    /**
     * A map of all baseurls used in different environments and servers
     * @var array
     */
    private static $environmentsMap = array(
        Environments::PRODUCTION => array(
            Servers::SERVER1 => 'https://petstore.swagger.io/v2',
            Servers::SERVER2 => 'http://petstore.swagger.io/v2',
            Servers::AUTH_SERVER => 'https://petstore.swagger.io/oauth',
        ),
    );
}
