<?php
/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SwaggerPetstoreLib;

/**
 * Baseurl aliases
 */
class Servers
{
    /**
     * TODO: Write general description for this element
     */
    const SERVER1 = "server1";

    /**
     * TODO: Write general description for this element
     */
    const SERVER2 = "server2";

    /**
     * TODO: Write general description for this element
     */
    const AUTH_SERVER = "auth server";
}
