<?php
/*
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace SwaggerPetstoreLib;

use SwaggerPetstoreLib\Controllers;

/**
 * SwaggerPetstoreLib client class
 */
class SwaggerPetstoreClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $oAuthClientId = null,
        $oAuthRedirectUri = null
    ) {
        Configuration::$oAuthClientId = $oAuthClientId ? $oAuthClientId : Configuration::$oAuthClientId;
        Configuration::$oAuthRedirectUri = $oAuthRedirectUri ? $oAuthRedirectUri : Configuration::$oAuthRedirectUri;
    }
    /**
     * Singleton access to Pet controller
     * @return Controllers\PetController The *Singleton* instance
     */
    public function getPet()
    {
        return Controllers\PetController::getInstance();
    }
    /**
     * Singleton access to Store controller
     * @return Controllers\StoreController The *Singleton* instance
     */
    public function getStore()
    {
        return Controllers\StoreController::getInstance();
    }
    /**
     * Singleton access to User controller
     * @return Controllers\UserController The *Singleton* instance
     */
    public function getUser()
    {
        return Controllers\UserController::getInstance();
    }
    /**
     * Get OAuth 2 authorization manager
     * @return OAuthManager
     */
    public function auth()
    {
        return OAuthManager::getInstance();
    }
}
